# Generated by Django 4.1.5 on 2023-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("impressions", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("clicks", models.IntegerField(blank=True, default=0, null=True)),
                ("date", models.DateField(blank=True, default=None, null=True)),
                ("cpc", models.FloatField(blank=True, default=0.0, null=True)),
                ("cpa", models.FloatField(blank=True, default=0.0, null=True)),
                ("roas", models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
